# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Tue Apr 29 14:47:24 2014
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmMainWindow(object):
    def setupUi(self, frmMainWindow):
        frmMainWindow.setObjectName(_fromUtf8("frmMainWindow"))
        frmMainWindow.resize(209, 170)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmMainWindow.sizePolicy().hasHeightForWidth())
        frmMainWindow.setSizePolicy(sizePolicy)
        frmMainWindow.setMinimumSize(QtCore.QSize(200, 170))
        self.tabWidget = QtGui.QTabWidget(frmMainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 131, 96))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblLayer_area = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLayer_area.sizePolicy().hasHeightForWidth())
        self.lblLayer_area.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLayer_area.setFont(font)
        self.lblLayer_area.setObjectName(_fromUtf8("lblLayer_area"))
        self.verticalLayout.addWidget(self.lblLayer_area)
        self.lblQuadratmeter = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQuadratmeter.sizePolicy().hasHeightForWidth())
        self.lblQuadratmeter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblQuadratmeter.setFont(font)
        self.lblQuadratmeter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblQuadratmeter.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblQuadratmeter.setFrameShadow(QtGui.QFrame.Raised)
        self.lblQuadratmeter.setText(_fromUtf8(""))
        self.lblQuadratmeter.setMargin(0)
        self.lblQuadratmeter.setObjectName(_fromUtf8("lblQuadratmeter"))
        self.verticalLayout.addWidget(self.lblQuadratmeter)
        self.lblHektar = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHektar.sizePolicy().hasHeightForWidth())
        self.lblHektar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblHektar.setFont(font)
        self.lblHektar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblHektar.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblHektar.setFrameShadow(QtGui.QFrame.Raised)
        self.lblHektar.setText(_fromUtf8(""))
        self.lblHektar.setObjectName(_fromUtf8("lblHektar"))
        self.verticalLayout.addWidget(self.lblHektar)
        self.lblQuadratkilometer = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQuadratkilometer.sizePolicy().hasHeightForWidth())
        self.lblQuadratkilometer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblQuadratkilometer.setFont(font)
        self.lblQuadratkilometer.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblQuadratkilometer.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblQuadratkilometer.setFrameShadow(QtGui.QFrame.Raised)
        self.lblQuadratkilometer.setText(_fromUtf8(""))
        self.lblQuadratkilometer.setObjectName(_fromUtf8("lblQuadratkilometer"))
        self.verticalLayout.addWidget(self.lblQuadratkilometer)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 10, 131, 71))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblLayer_perimeter = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLayer_perimeter.sizePolicy().hasHeightForWidth())
        self.lblLayer_perimeter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLayer_perimeter.setFont(font)
        self.lblLayer_perimeter.setObjectName(_fromUtf8("lblLayer_perimeter"))
        self.verticalLayout_2.addWidget(self.lblLayer_perimeter)
        self.lblMeter = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMeter.sizePolicy().hasHeightForWidth())
        self.lblMeter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMeter.setFont(font)
        self.lblMeter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblMeter.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblMeter.setFrameShadow(QtGui.QFrame.Raised)
        self.lblMeter.setText(_fromUtf8(""))
        self.lblMeter.setMargin(0)
        self.lblMeter.setObjectName(_fromUtf8("lblMeter"))
        self.verticalLayout_2.addWidget(self.lblMeter)
        self.lblKilometer = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblKilometer.sizePolicy().hasHeightForWidth())
        self.lblKilometer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblKilometer.setFont(font)
        self.lblKilometer.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblKilometer.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblKilometer.setFrameShadow(QtGui.QFrame.Raised)
        self.lblKilometer.setText(_fromUtf8(""))
        self.lblKilometer.setObjectName(_fromUtf8("lblKilometer"))
        self.verticalLayout_2.addWidget(self.lblKilometer)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(frmMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMainWindow)

    def retranslateUi(self, frmMainWindow):
        frmMainWindow.setWindowTitle(QtGui.QApplication.translate("frmMainWindow", "Calc Area", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLayer_area.setText(QtGui.QApplication.translate("frmMainWindow", "Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("frmMainWindow", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLayer_perimeter.setText(QtGui.QApplication.translate("frmMainWindow", "Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("frmMainWindow", "Perimeter", None, QtGui.QApplication.UnicodeUTF8))

